#服务器端口
server:
  port: 10231

#数据源配置
spring:
  datasource:
    url: ${blade.datasource.dev.url}
    username: ${blade.datasource.dev.username}
    password: ${blade.datasource.dev.password}
  rabbitmq:
    host: 192.168.247.184
    port: 5672
    username: admin
    password: admin
    virtual-host: /
    connection-timeout: 5000
